filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/access.log

setup.kibana:
  host: "kibana:5601"

setup.template.name: "filebeat-nginx"
setup.template.pattern: "filebeat-nginx-*"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "filebeat-nginx-%{+yyyy.MM.dd}"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~